name: visit_uzbekistan
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.6.0
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8

  bot_toast: 4.1.3

  chopper: 7.4.0

  equatable: 2.0.7

  flutter_bloc: 8.1.6

  flutter_downloader: 1.11.8

  flutter_gen: 5.3.2

  flutter_dialogs: 3.0.0

  flutter_localization: 0.1.14

  flutter_screenutil: 5.9.0

  flutter_svg: 2.0.9
 
  http: 1.2.2

  hive: 2.2.3

  hive_flutter: 1.1.0

  package_info_plus: 4.2.0

  path_provider: 2.1.4

  intl: 0.19.0

  permission_handler: 11.3.1

  json_annotation: 4.8.1

  logging: 1.2.0

  shared_preferences: 2.2.2

  url_launcher: 6.1.4

  iconsax_plus: 1.0.0

  get_it: 8.0.3

  injectable: 2.5.0

  geolocator: 13.0.4

  introduction_screen: 3.1.14

  google_sign_in: 6.1.6

  # flutter_html: ^3.0.0-beta.2
  flutter_widget_from_html_core: 0.16.0

  webview_flutter: 4.13.0

  cached_network_image: 3.4.1

  internet_connection_checker: ^3.0.1




dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: 2.4.11

  chopper_generator: 7.4.0

  flutter_gen_runner: 5.3.2

  json_serializable: 6.7.1

  hive_generator: 2.0.1

  arb_generator: 0.0.3

  injectable_generator: 2.6.2


flutter_gen:
  output: lib/gen/ 
  line_length: 80 

arb_generator:
  input_filepath: "assets/localization/localization.csv"
  output_directory: "lib/l10n"
  filename_prepend: "app_"
  csv_settings:
    delimiter: ","
    base_index: 1
    

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/icons/
    - assets/icons/single_city/
    - assets/icons/auth/
    - assets/icons/flags/
    - assets/images/
    - assets/map/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Thin.ttf
          weight: 100
        - asset: assets/fonts/Montserrat-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Montserrat-Light.ttf
          weight: 300
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Montserrat-Black.ttf
          weight: 900
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/ic_launcher_ios.jpg"
  image_path_android: "assets/icons/ic_launcher_android.png"
  min_sdk_android: 21