name: visit_uzbekistan
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.6.0
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  auto_size_text: 3.0.0

  bot_toast: 4.1.3

  qr_code_scanner_plus: ^2.0.10+1

  chopper: 7.4.0

  equatable: 2.0.5

  flutter_bloc: 8.1.6

  flutter_downloader: 1.11.8

  flutter_gen: 5.3.2

  flutter_dialogs: 3.0.0

  flutter_localization: 0.1.14

  flutter_screenutil: 5.9.0

  flutter_svg: 2.0.9
 
  http: 1.2.2

  hive: 2.2.3

  hive_flutter: 1.1.0

  open_file: 3.5.10

  package_info_plus: 4.2.0

  path_provider: 2.1.4

  intl: 0.19.0

  percent_indicator: 4.2.3

  permission_handler: 11.3.1

  json_annotation: 4.8.1

  logging: 1.2.0

  local_auth: 2.3.0

  shared_preferences: 2.2.2

  shimmer: 3.0.0

  url_launcher: 6.1.4

  iconsax_plus: 1.0.0

  get_it: 8.0.3

  injectable: ^2.5.0

  geolocator: 13.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: 2.4.11

  chopper_generator: 7.4.0

  flutter_gen_runner: 5.3.2

  json_serializable: 6.7.1

  hive_generator: 2.0.1

  arb_generator: 0.0.3

  injectable_generator: 2.6.2

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
